# Configuration for a local fabric network.
version: '2.1'
services:
  sandbox_oracle:
    extends:
      file: common.yaml
      service: sandbox_oracle
    ports:
    - "8080:8080" # expose this for testing purposes
    - "9600:9600" # expose this for testing purposes
    environment:
    - SANDBOX_ORACLE_EMULATE_CC=false
    networks:
    - byfn
networks:
  byfn:
    name: byfn
    external: true
